export const ACTIVITY_ACTION_TYPES = [
  'CHECKED_STUDENT',
  'PAYMENT_RECEIVED',
  'MEMBERSHIP_EXPIRED',
  'NEW_MEMBER_ADDED',
  'MEMBER_UPDATED',
  'MEMBER_REMOVED',
  'LIBRARY_CREATED',
  'LIBRARY_UPDATED',
  'USER_LOGGED_IN',
  'USER_LOGGED_OUT',
  'BOOKING_APPROVED',
  'BOOKING_REJECTED',
  'BOOKING_CANCELLED',
  'LIBRARY_GEOFENCE_UPDATED',
  'LEAVE_REQUEST_RAISED',
] as const;

export type ActivityActionType = (typeof ACTIVITY_ACTION_TYPES)[number];
